ebpf: support libbpf 1.0+
if libbpf 1.0+ is installed, configure fail
to probe XDP support and result in error

/usr/bin/ld: runmode-af-packet.o: in function `ParseAFPConfig':
runmode-af-packet.c:(.text+0x1337): undefined reference to `EBPFUpdateFlow'
/usr/bin/ld: source-af-packet.o: in function `AFPBypassCallback':
source-af-packet.c:(.text+0x2cd1): undefined reference to `EBPFUpdateFlow'
/usr/bin/ld: source-af-packet.c:(.text+0x2e9a): undefined reference to `EBPFUpdateFlow'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

update to make support libbpf 1.0+